title: Doehyun Baek
logo: /assets/img/headshot.jpeg
show_downloads: false
# plugins:
#    - jekyll-remote-theme
    # - jekyll-optional-front-matter
    # - jekyll-redirect-from
    # - jekyll-feed
theme: jekyll-theme-minimal
description: I am a PhD student at the <a href="https://cispa.de/en" target=_blank>CISPA Helmholtz Center for Information Security</a>, advised by <a href="https://software-lab.org/people/Michael_Pradel.html" target=_blank>Prof. Dr. Michael Pradel</a>
contact_links: |
    <i class="fa fa-envelope-o fa-fw" aria-hidden="true" title="Mail"></i>
    <span class="sr-only">Mail:</span>&nbsp;&nbsp;<a href="mailto:doehyunbaek@gmail.com" title="Mail">doehyunbaek@gmail.com</a> <br>
    <i class="fa fa-github fa-fw" aria-hidden="true" title="GitHub"></i>
    <span class="sr-only">GitHub:</span>&nbsp;&nbsp;<a href="https://github.com/doehyunbaek" title="GitHub" target="_blank">doehyunbaek</a><br>
